version: 2.1
#########
# Common
#########
orbs:
  heroku: circleci/heroku@1.0.1
############
# Workflows
############
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
##################
# Job Definitions
##################
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - 'venv'
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - add_ssh_keys:
          fingerprints:
            - $SSH_KEY
      - heroku/install
      - heroku/deploy-via-git:
          force: true